### ISSUE TITLE
Error with virtual env

### ISSUE THREAD

**Issue by aj-in** [shyam999/Hot-Food#13]
what do I do? (I'm an absolute beginner to Django please do help)
I keep getting these errors
1)when I open the terminal in vs code 
I cant install virtual env
2) I use a windows machine n u wrote sudo commands 
so do( I need a Linux machine or an ISO virtual environment)
and then paste all the commands in Linux terminal??
![Screenshot 2020-11-18 185446](https://user-images.githubusercontent.com/74534547/99536630-9f734480-29d0-11eb-9826-4571f6c3d9fa.jpg)

**Comment by shyam999** [comment]
I have updated the docs to make the installation easier, check out the
readme.

and in windows dont use sudo just open the cmd as administrator(the rest of
the command will remain same)

Regards,
Shyam Acharjya

**Comment by aj-in** [comment]
as u said "
and in windows dont use sudo just open the cmd as administrator(the rest of
the command will remain same)
"
what about step 3
sudo doesn't work with windows command prompt
anyways i downloaded the rabbit mq from github but
service command doesn't work on windows command prompt
![Screenshot 2020-11-20 181459](https://user-images.githubusercontent.com/74534547/99801870-b8a8fc00-2b5c-11eb-81b2-e673a0b23ac4.jpg)

please help

**Comment by shyam999** [comment]
checkout rabbitmq's official docs, they have clear instructions for windows.

Regards
Shyam Acharjya

**Comment by aj-in** [comment]
i did read their docs , i installed erlang added it to path, ran rabbit mq server (using username guest and password guest )
now i get this error
![edited](https://user-images.githubusercontent.com/74534547/99807788-feb68d80-2b65-11eb-9ec4-d79766929770.jpg)

can you please help me sir , also can u confirm that the steps i used to install are correct?

**Comment by tiwari1302** [comment]
Creare

> i did read their docs , i installed erlang added it to path, ran rabbit mq server (using username guest and password guest )
> now i get this error
> ![edited](https://user-images.githubusercontent.com/74534547/99807788-feb68d80-2b65-11eb-9ec4-d79766929770.jpg)
> 
> can you please help me sir , also can u confirm that the steps i used to install are correct?

1. Create a file with name as .env 
2. Paste the following contents to it:
```
SECRET_KEY=YOUR_OWN_SECRET_KEY
DEBUG=True
OTHER_VARIABLE=variable_1
```
Secret key can be generated by: https://miniwebtool.com/django-secret-key-generator/

And then it should probably work.
Good luck!
