### ISSUE TITLE
can't go to admin page

### ISSUE THREAD

**Issue by tiwari1302** [shyam999/Hot-Food#26]
when I want to go to http://127.0.0.1:8000/admin , it throws me to an error page
![image](https://user-images.githubusercontent.com/60061690/124108628-f6bbb600-da83-11eb-91f8-94bb0366225c.png)
What could be the issue?

**Comment by tangpongpat** [comment]
**in src/myproject** 
INSTALLED_APPS  
'django.contrib.sites' to 'django.contrib' 
**it work for me**

**Comment by shyam999** [comment]
will check
