### ISSUE TITLE
I am unable to start the server. Please help!

### ISSUE THREAD

**Issue by Shubhamverma2796** [shyam999/Hot-Food#7]
Whenever I am trying to run the server, I am getting the following error :
ImportError: cannot import name 'Celery' from 'celery' (C:\Open source\Hot-Food\env\lib\site-packages\celery\__init__.py)
![Screenshot (457)](https://user-images.githubusercontent.com/54266411/94816216-1ea8bb00-0419-11eb-80da-327622523785.png)

**Comment by Marlysson** [comment]
@Shubhamverma2796 Did you install celery library?

**Comment by shyam999** [comment]
> Whenever I am trying to run the server, I am getting the following error :
> ImportError: cannot import name 'Celery' from 'celery' (C:\Open source\Hot-Food\env\lib\site-packages\celery__init__.py)
> ![Screenshot (457)](https://user-images.githubusercontent.com/54266411/94816216-1ea8bb00-0419-11eb-80da-327622523785.png)

try '''pip install django-celery'''..see if that resolves your issue..If it doesn't let me know

**Comment by IamOmaR22** [comment]
pip install django-celery

**Comment by shyam999** [comment]
i'm closing this issue...if anyone in the future face similar error reopen this issue
